### ISSUE TITLE
Mind creating a tag?

### ISSUE THREAD

**Issue by atufkas** [dmeybohm/dot-notation#1]
Hi David,

thanks for this piece of software I'm currently using in one of my projects. My question is simply: Would you mind creating a tag (v1.0.0 or whatever) - That would enable me to seamlessly integrate your project with composer using a semantic version string and standard minimum stability settings...

Thanks in advance & code on!
Matthias

**Comment by dmeybohm** [comment]
Hi Mattias,

Thanks for using it! No problem. I created a v1.0.0 tag.

Dave

**Comment by atufkas** [comment]
:+1: Thanks a lot and sorry for not responding last time when you created the tag...!
